FROM golang:1.10

MAINTAINER Adrien Domoison "adomoison@gmail.com"

WORKDIR /go/src/github.com/adriendomoison/apigoboot/api-gateway

CMD go build ./serve-api-gateway.go && ./serve-api-gateway

EXPOSE 4200