// Package servicehelper structure the construction of errors generated by services
package servicehelper

// Code describe the status that will be generated in the BuildResponseError for the http response
type Code uint

// Code describe the status that will be generated in the BuildResponseError for the http response
const (
	Processing      Code = 102
	BadRequest           = 400
	Unauthorized         = 401
	Forbidden            = 403
	NotFound             = 404
	AlreadyExist         = 409
	UnexpectedError      = 500
	NotImplemented       = 501
)

// Error describe the error object returned from services that can be passed directly to the BuildResponseError method
type Error struct {
	Param   string
	Detail  error
	Message string
	Code    Code
}
