language: go
go:
  - "1.10"

addons:
  hosts:
    - api.go.boot

before_script:
  - psql -c "CREATE DATABASE apigoboot_test;" -U postgres
  - psql -c "CREATE USER apigoboot_test WITH PASSWORD 'apigoboot_test';" -U postgres

before_install:
  - go get github.com/mattn/goveralls

script:p
  - $GOPATH/bin/goveralls -service=travis-ci