version: '3'
services:
  db:
    build: ./postgres
    volumes:
      - ./postgres/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apigoboot
      - POSTGRES_PASSWORD=apigoboot
      - PGDATA=/pgdata

  user_api:
    build:
      context: ./user-micro-service
    volumes:
      - ./user-micro-service:/go/src/github.com/adriendomoison/apigoboot/user-micro-service/
    ports:
      - "4200:4200"
    links:
      - db

  profile_api:
    build:
      context: ./profile-micro-service
    volumes:
      - ./profile-micro-service:/go/src/github.com/adriendomoison/apigoboot/profile-micro-service/
    ports:
      - "4201:4201"
    links:
      - db

  oauth2_api:
    build:
      context: ./oauth2-micro-service
    volumes:
      - ./oauth2-micro-service:/go/src/github.com/adriendomoison/apigoboot/oauth2-micro-service/
    ports:
      - "4202:4202"
    links:
      - db