version: '3'
services:
  db:
    build: api-db
    container_name: apigoboot_db
    volumes:
      - ./api-db/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apigoboot
      - POSTGRES_PASSWORD=apigoboot
      - PGDATA=/pgdata

  api_gateway:
    build:
      context: ./api-gateway
    container_name: apigoboot_api_gateway
    depends_on:
      - "db"
    volumes:
      - ./api-gateway:/go/src/github.com/adriendomoison/apigoboot/api-gateway/
    ports:
      - "4200:4200"
    networks:
      default:
        aliases:
          - gateway.api

  api_user:
    build:
      context: ./user-micro-service
    container_name: apigoboot_api_user
    depends_on:
      - "db"
    volumes:
      - ./user-micro-service:/go/src/github.com/adriendomoison/apigoboot/user-micro-service/
    ports:
      - "4201:4200"
    links:
      - db
    networks:
      default:
        aliases:
          - user.api

  api_profile:
    build:
      context: ./profile-micro-service
    container_name: apigoboot_api_profile
    depends_on:
      - "db"
    volumes:
      - ./profile-micro-service:/go/src/github.com/adriendomoison/apigoboot/profile-micro-service/
    ports:
      - "4202:4200"
    links:
      - db
    networks:
      default:
        aliases:
          - profile.api

  api_oauth2:
    build:
      context: ./oauth2-micro-service
    container_name: apigoboot_api_oauth2
    volumes:
      - ./oauth2-micro-service:/go/src/github.com/adriendomoison/apigoboot/oauth2-micro-service/
    ports:
      - "4203:4200"
    links:
      - db
    networks:
      default:
        aliases:
          - oauth2.api
networks:
  default:
    external:
      name: apigoboot_network