/*
	servicehelper structure the construction of errors generated by services
*/
package servicehelper

// code describe the status that will be generated in the BuildResponseError for the http response
type code uint

const (
	BadRequest      code = iota
	NotFound
	AlreadyExist
	UnexpectedError
)

// Error describe the error object returned from services that can be passed directly to the BuildResponseError method
type Error struct {
	Param   string
	Detail  error
	Message string
	Code    code
}
